# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uk.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Universal_calculator(object):
    def setupUi(self, Universal_calculator):
        Universal_calculator.setObjectName("Universal_calculator")
        Universal_calculator.resize(1150, 579)
        font = QtGui.QFont()
        font.setPointSize(8)
        Universal_calculator.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Universal_calculator)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(40, 30, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(160, 30, 981, 51))
        self.lcdNumber.setDigitCount(38)
        self.lcdNumber.setObjectName("lcdNumber")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 90, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 60, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 140, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 190, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 240, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 290, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 340, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 390, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 440, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 490, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(240, 140, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(240, 390, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(240, 190, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(240, 290, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(240, 240, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(240, 440, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(240, 340, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(240, 490, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(240, 90, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(470, 90, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(470, 140, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(470, 190, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(470, 240, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(470, 290, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_24.setGeometry(QtCore.QRect(470, 340, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_25.setGeometry(QtCore.QRect(470, 390, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_26.setGeometry(QtCore.QRect(470, 440, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_27.setGeometry(QtCore.QRect(470, 490, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_28.setGeometry(QtCore.QRect(930, 390, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_29.setGeometry(QtCore.QRect(700, 190, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_30.setGeometry(QtCore.QRect(700, 240, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_31.setGeometry(QtCore.QRect(700, 290, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_32.setGeometry(QtCore.QRect(700, 340, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_32.setFont(font)
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_33 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_33.setGeometry(QtCore.QRect(700, 390, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_33.setFont(font)
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_34 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_34.setGeometry(QtCore.QRect(700, 440, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_34.setFont(font)
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_35 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_35.setGeometry(QtCore.QRect(700, 490, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_35.setFont(font)
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_36 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_36.setGeometry(QtCore.QRect(930, 440, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_36.setFont(font)
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_37 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_37.setGeometry(QtCore.QRect(930, 90, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_37.setFont(font)
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_38 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_38.setGeometry(QtCore.QRect(930, 140, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_38.setFont(font)
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_39 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_39.setGeometry(QtCore.QRect(930, 190, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_39.setFont(font)
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_40 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_40.setGeometry(QtCore.QRect(930, 240, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_40.setFont(font)
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_41 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_41.setGeometry(QtCore.QRect(930, 290, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_41.setFont(font)
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_42 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_42.setGeometry(QtCore.QRect(930, 340, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_42.setFont(font)
        self.pushButton_42.setObjectName("pushButton_42")
        self.pushButton_45 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_45.setGeometry(QtCore.QRect(930, 490, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_45.setFont(font)
        self.pushButton_45.setObjectName("pushButton_45")
        self.pushButton_43 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_43.setGeometry(QtCore.QRect(700, 90, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_43.setFont(font)
        self.pushButton_43.setObjectName("pushButton_43")
        self.pushButton_44 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_44.setGeometry(QtCore.QRect(700, 140, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_44.setFont(font)
        self.pushButton_44.setObjectName("pushButton_44")
        self.pushButton_64 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_64.setGeometry(QtCore.QRect(1220, 580, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_64.setFont(font)
        self.pushButton_64.setObjectName("pushButton_64")
        self.pushButton_70 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_70.setGeometry(QtCore.QRect(1210, 620, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_70.setFont(font)
        self.pushButton_70.setObjectName("pushButton_70")
        Universal_calculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Universal_calculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1150, 21))
        self.menubar.setObjectName("menubar")
        Universal_calculator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Universal_calculator)
        self.statusbar.setObjectName("statusbar")
        Universal_calculator.setStatusBar(self.statusbar)

        self.retranslateUi(Universal_calculator)
        QtCore.QMetaObject.connectSlotsByName(Universal_calculator)

    def retranslateUi(self, Universal_calculator):
        _translate = QtCore.QCoreApplication.translate
        Universal_calculator.setWindowTitle(_translate("Universal_calculator", "MainWindow"))
        self.label.setText(_translate("Universal_calculator", "x"))
        self.pushButton.setText(_translate("Universal_calculator", "x + y"))
        self.label_2.setText(_translate("Universal_calculator", "y"))
        self.pushButton_2.setText(_translate("Universal_calculator", "x - y"))
        self.pushButton_3.setText(_translate("Universal_calculator", "x * y"))
        self.pushButton_4.setText(_translate("Universal_calculator", "x / y"))
        self.pushButton_5.setText(_translate("Universal_calculator", "x ** y"))
        self.pushButton_6.setText(_translate("Universal_calculator", "sqrt(x)"))
        self.pushButton_7.setText(_translate("Universal_calculator", "sqrt(y)"))
        self.pushButton_8.setText(_translate("Universal_calculator", "x!"))
        self.pushButton_9.setText(_translate("Universal_calculator", "y!"))
        self.pushButton_10.setText(_translate("Universal_calculator", "-y"))
        self.pushButton_11.setText(_translate("Universal_calculator", "x ** 3"))
        self.pushButton_12.setText(_translate("Universal_calculator", "%x"))
        self.pushButton_13.setText(_translate("Universal_calculator", "x ** 2"))
        self.pushButton_14.setText(_translate("Universal_calculator", "%y"))
        self.pushButton_15.setText(_translate("Universal_calculator", "y ** 3"))
        self.pushButton_16.setText(_translate("Universal_calculator", "y ** 2"))
        self.pushButton_17.setText(_translate("Universal_calculator", "pi"))
        self.pushButton_18.setText(_translate("Universal_calculator", "-x"))
        self.pushButton_19.setText(_translate("Universal_calculator", "1 / x"))
        self.pushButton_20.setText(_translate("Universal_calculator", "1 / y"))
        self.pushButton_21.setText(_translate("Universal_calculator", "10 ** x"))
        self.pushButton_22.setText(_translate("Universal_calculator", "10 ** y"))
        self.pushButton_23.setText(_translate("Universal_calculator", "|x|"))
        self.pushButton_24.setText(_translate("Universal_calculator", "|y|"))
        self.pushButton_25.setText(_translate("Universal_calculator", "округление х"))
        self.pushButton_26.setText(_translate("Universal_calculator", "округление у"))
        self.pushButton_27.setText(_translate("Universal_calculator", "e"))
        self.pushButton_28.setText(_translate("Universal_calculator", "tg x"))
        self.pushButton_29.setText(_translate("Universal_calculator", "округление х вниз"))
        self.pushButton_30.setText(_translate("Universal_calculator", "округление у вниз"))
        self.pushButton_31.setText(_translate("Universal_calculator", "x // y"))
        self.pushButton_32.setText(_translate("Universal_calculator", "x % y"))
        self.pushButton_33.setText(_translate("Universal_calculator", "y // x"))
        self.pushButton_34.setText(_translate("Universal_calculator", "y % x"))
        self.pushButton_35.setText(_translate("Universal_calculator", "y - x"))
        self.pushButton_36.setText(_translate("Universal_calculator", "tg y"))
        self.pushButton_37.setText(_translate("Universal_calculator", "целая часть от х"))
        self.pushButton_38.setText(_translate("Universal_calculator", "целая часть от у"))
        self.pushButton_39.setText(_translate("Universal_calculator", "sin x"))
        self.pushButton_40.setText(_translate("Universal_calculator", "sin y"))
        self.pushButton_41.setText(_translate("Universal_calculator", "cos x"))
        self.pushButton_42.setText(_translate("Universal_calculator", "cos y"))
        self.pushButton_45.setText(_translate("Universal_calculator", "золотое сечение"))
        self.pushButton_43.setText(_translate("Universal_calculator", "x - простое число ?"))
        self.pushButton_44.setText(_translate("Universal_calculator", "y - простое число ?"))
        self.pushButton_64.setText(_translate("Universal_calculator", "- (у)"))
        self.pushButton_70.setText(_translate("Universal_calculator", "ac (y)"))

